openapi: 3.0.3
info:
  title: Go-Sentinel API
  version: 1.0.0
  description: API documentation for Go-Sentinel.
servers:
  - url: http://localhost:8080
paths:
  /health:
    get:
      summary: Health check endpoint
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: ok
  /metrics:
    get:
      summary: Metrics endpoint
      responses:
        '200':
          description: Prometheus metrics
          content:
            text/plain:
              schema:
                type: string
                example: |
                  go_mem_alloc_bytes 123456
                  go_goroutines 12
                  api_total_requests 42
                  api_total_errors 0
