# .air.toml for Go Sentinel
root = "."
tmp_dir = "tmp"

[build]
  # First run linter, then tests, then build the binary
  pre_cmd = [
    "golangci-lint run --timeout=2m",
    "go test -tags=integration ./..."
  ]
  cmd = "go build -o ./tmp/main.exe ./cmd/go-sentinel-web"
  bin = "./tmp/main.exe"
  # Stop if linting or tests fail
  stop_on_error = true
  # Show error message in terminal
  error_length = 10000

[run]
# run the binary
  cmd = "./tmp/main.exe"

[watch]
  delay = 1000
  includes = ["**/*.go", "**/*.html", "**/*.tmpl", "**/*.css", "**/*.js", "**/*.ts", "**/*.json"]
  excludes = ["tmp/**", ".git/**", "vendor/**", "**/node_modules/**"]

[log]
  color = true
  time = true
  level = "debug" # debug, info, warn, error

[misc]
  # clean the tmp directory on exit
  clean_on_exit = true



