version: "2"
run:
  timeout: 5m
linters:
  enable:
    # Enabled by default
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    
    # Additional linters
    - misspell
    - revive
    - gocyclo