version: 2.1.6
run:
  timeout: 5m
linters:
  enable:
    - govet
    - golint
    - gofmt
    - staticcheck
    - errcheck
    - unused
    - deadcode
    - gocyclo
    - ineffassign
    - structcheck
    - varcheck
    - typecheck
    - misspell
    - revive
