version: "2"
run:
  timeout: 5m
linters:
  enable:
    - govet
    - golint
    - staticcheck
    - errcheck
    - unused
    - deadcode
    - gocyclo
    - ineffassign
    - structcheck
    - varcheck
    - misspell
    - revive